### ISSUE TITLE
Missing CPD attributes

### ISSUE THREAD

**Issue by sbonnick** [aaschmid/gradle-cpd-plugin#11]
Hi, 

I've noticed this plugin only really supports the "encoding", "format" and "minimumtokencount". Do you have plans to add any additional attributes as defined on [cpd-usage](http://pmd.sourceforge.net/pmd-5.0.5/cpd-usage.html) page?

Specifically, I am most interested in "ignoreAnnotations" and "ignoreLiterals".

Thanks

**Comment by aaschmid** [comment]
Hi @sbonnick, 
yes, I can add these attributes. The only thing is, that I am not really sure if they work properly. May obervations are not very optimistic for these attributes. What are your observations? 

Nevertheless, I will make them available asap.

Cheers,
Andreas

**Comment by sbonnick** [comment]
Hi Andreas,

To be honest I haven't used these commands previously. My hope is that I
can use these commands to "ignore" matching of licence headers in source
code.

-Stewart

**Comment by aaschmid** [comment]
Good news, the parameters are working very well and I have almost finished the implementation on this ;-)

**Comment by sbonnick** [comment]
Excellent news. I will give it a try once up on maven.

**Comment by sbonnick** [comment]
Tried with latest 0.4 build, new features work great!

**Comment by aaschmid** [comment]
Thanks, if you like, i would appretiate your voting on https://bintray.com/aaschmid/gradle-plugins/gradle-cpd-plugin/view :-)
