### ISSUE TITLE
Missing CPD attributes

### ISSUE THREAD

**Issue by gregory-ewing** [aaschmid/gradle-cpd-plugin#12]
Hello,

Would it be possible to integrate the "skipLexicalErrors" attribute into your plugin (No such property: skipLexicalErrors for class: de.aaschmid.gradle.plugins.cpd.Cpd_Decorated). 

Thank you.

**Comment by aaschmid** [comment]
Hi @gregory-ewing, yes of course. I just do not have so much time at the moment but I will do my best to fix it as soon as possible. Do you have any time constraints, though?

**Comment by gregory-ewing** [comment]
Hi @aaschmid, thank you getting back to me so quickly. Regarding time constraints, ideally the end of the month. However, i will need it (no pressure) before the 14th September if possible.

Thanks, Greg.

**Comment by aaschmid** [comment]
Hi @gregory-ewing, I have added two further attributes, see 58e281d. It would be nice if you could test the version before I create a new release (even if I have written automated tests).

You can do that by adding 

```
buildscript {
    repositories {
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'de.aaschmid.gradle.plugins:gradle-cpd-plugin:0.5-SNAPSHOT'
    }
}
apply plugin: 'cpd'
``` 

to your Gradle build script.

**Comment by gregory-ewing** [comment]
Hello @aaschmid, i have just carried out some preliminary tests with the "de.aaschmid.gradle.plugins:gradle-cpd-plugin:0.5-SNAPSHOT" version using both the skipDuplicateFiles and skipLexicalErrors attributes and it seems to work fine.
I will keep you posted once i have carried out further tests (tomorrow).

Thank you for your reactivity.
Regards.

**Comment by gregory-ewing** [comment]
Hi @aaschmid, i have finished my tests (sorry for the delay) with the new plugin. This version works fine. You have my approval for the new version.
Regards.

**Comment by aaschmid** [comment]
Great, thanks for the feedback. The new release is ready for use!
