### ISSUE TITLE
How to disable cpdCheck

### ISSUE THREAD

**Issue by JerryShea** [aaschmid/gradle-cpd-plugin#16]
Hi, thanks for the plugin... It works well!

However, I can't get my use case to work. I want to run cpdCheck explicitly (e.g. gradle cpdCheck) but I don't want cpdCheck task to run when I run - for example - gradle build.
My cpdCheck stanza looks like this
```
cpdCheck() {
    enabled = cpd_enabled
    reports {
        csv.enabled = false
        text.enabled = true
        xml.enabled = false
    }
}
```
but unfortunately the cpd_enabled variable always seems to be ignored - if I set it to false in gradle.properties or on the command line then cpdCheck still runs.
Is there any way to turn off cpdCheck by default so that I can explicitly turn it on only when I need it?

Thanks, Jerry

**Comment by aaschmid** [comment]
Hi @JerryShea, thanks for the request. I will try to fix it until the next weeks, however having a quick look, it is strange. Because normally every ```SourceTask``` has the ```enabled``` feature out of the box ...

**Comment by aaschmid** [comment]
Hi @JerryShea, while looking deeper into this issue, I found out that the enabled is working fine. The problem though is that variables in Gradle are first interpreted as ```String```s. This means that 
the ```String``` of ```cpd_enabled``` is interpreted as ```"true"``` or ```"false"```, respectively). According to [Groovy Truth](http://groovy-lang.org/semantics.html#Groovy-Truth) every non-empty ```String``` evaluates to ```true``` such that ```cpd.enabled``` is always set to ```true```. 

So you need to convert this by your own. I would recommend something like the following to have a fallback if the property is not set:

``` 
ext.testEnabled = false
if (hasProperty('test_enabled')) {
    println("test_enabled property: ${test_enabled}")
    ext.testEnabled = true
} else {       
    println('test_enabled not available')                                                                                                                                                      
}              
println("testEnabled: ${testEnabled}")
               
task test {  
    enabled = testEnabled
} 
``` 

Does that help?

**Comment by JerryShea** [comment]
Wow thanks Andreas. Apologies for wasting your time!

**Comment by aaschmid** [comment]
No worries :-)
Please don't hesitate to contact me if you have any further issues.

I will close this issue.
