### ISSUE TITLE
Change groupId to "de.aaschmid"

### ISSUE THREAD

**Issue by aaschmid** [aaschmid/gradle-cpd-plugin#19]
As you normally use the Gradle Plugin notation and therefore ```de.aaschmid.cpd``` this will only affect users using the old way of including plugins ...

Sorry, for any inconvenience!

**Comment by r-tock** [comment]
I am having issues 

```
* What went wrong:
Plugin [id: 'de.aaschmid.cpd', version: '1.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (plugin 'de.aaschmid.cpd' has no version '1.0' - see https://plugins.gradle.org/plugin/de.aaschmid.cpd for available versions)


```

**Comment by aaschmid** [comment]
Unfortunately, the plugin seems not to be approved yet. Don't know how long this will take. Please be patient and use version 0.5 till it appears on https://plugins.gradle.org/search?term=cpd.

**Comment by r-tock** [comment]
yeah, can't use 0.5 as we are not on gradle 2.14. Disabled cpd in our continuous builds until this is available.

**Comment by aaschmid** [comment]
I will try to clarify as soon as possible ...

**Comment by aaschmid** [comment]
@r-tock now it should work :-)
have fun using it
