### ISSUE TITLE
I try to use a different notation but it does not work...

### ISSUE THREAD

**Issue by OleksandrKucherenko** [aaschmid/gradle-cpd-plugin#2]
I try to make gradle configuration similar to other Code Quality tools. 
Example:

task checkstyle(type: Checkstyle) {
  description = 'execute checkstyle tool on project source code'
  group = 'Code Quality'
}

task findbugs(type: FindBugs, dependsOn: ['assembleDebug']) {
  description = 'execute findbugs tool on project compiled code'
  group = 'Code Quality'
}

task pmd(type: Pmd) {
  description = 'execute PMD tool on project source code'
  group = 'Code Quality'
}

But when i try to create cpd task in such way: 

task cpd(type: Cpd) {
  description = 'execute CPD (copy/paste duplicates) tool on project code'
  group = 'Code Quality'
}

I got gradle error. Can you suggest how to workaround the issue?

**Comment by aaschmid** [comment]
Close due to no further response.
