### ISSUE TITLE
Could not find property 'Cpd' on root project ...

### ISSUE THREAD

**Issue by ChristianWulf** [aaschmid/gradle-cpd-plugin#21]
`tasks.withType(Cpd) `
does not work, because gradle does not seem to know the class Cpd.

**Comment by aaschmid** [comment]
Hi @ChristianWulf, you need to either `import de.aaschmid.gradle.plugins.cpd.Cpd` or use 

```
tasks.withType(de.aaschmid.gradle.plugins.cpd.Cpd) {                                                                                                                                       
    println it                                
}
```

Does that solve your problem?

Cheers,
Andreas

**Comment by ChristianWulf** [comment]
Yes, thanks. However, the source attribute is not accepted:
```gradle
tasks.withType(de.aaschmid.gradle.plugins.cpd.Cpd) {                                                                                                                                       
		reports {
		    xml.enabled = true
		    text.enabled = false
		}
		source = files('src')
}
```

**Comment by aaschmid** [comment]
Sorry, cannot reproduce. For me works the following `build.gradle`:

```
plugins {
    id 'de.aaschmid.cpd' version '1.0'
}
repositories {
    mavenCentral()
}
cpd {
    minimumTokenCount = 10
}
tasks.withType(de.aaschmid.gradle.plugins.cpd.Cpd) {
    reports {
        xml.enabled = true
        text.enabled = false
    }
    source = files('src')
}
```

Now create the following source file as `Hello.java` and `Hello2.java`:

```
public class Hello {
    public static void main(String[] args) {
        System.out.println("This is a test!");
    }
}
```

**Comment by aaschmid** [comment]
Hi @ChristianWulf, has that helped?

**Comment by ChristianWulf** [comment]
I have checked that the source attribute contains files within the 'src' folder only. That's great. Nevertheless, I get the following error:
```gradle
Execution failed for task ':cpdCheck'.
> Lexical error in file C:\Users\chw\git\kieker\kieker-monitoring\test\kieker\test\monitoring\junit\probe\spring\executions\jetty\webapp\jetty.xml at line 8, column 28.  Encountered: "\r" (13), after : "\""
```
As you can see, it tries to read files within the "test" folder.

**Comment by aaschmid** [comment]
puh ... is the source code open source or available somewhere such that I can check it directly. Otherwise it get's quite hard to reproduce.

Can you at least past the relevant parts of your `build.gradle` here (all parts dealing with `CPD` somehow)?

What kind of project is it? For a Java / JVM project you can try

```
cpdCheck {
    reports {
        xml.enabled = true
        text.enabled = false
    }
    source = sourceSets.main.allJava // only java, groovy and scala classes in 'main' sourceSets
}
```

**Comment by ChristianWulf** [comment]
Yes, you can use the stable branch of [https://github.com/kieker-monitoring/kieker](https://github.com/kieker-monitoring/kieker). At the root level, you can insert and test your proposed code snippets.

**Comment by aaschmid** [comment]
Hi @ChristianWulf, 

good things come to those who wait. I eventually fixed your problem by cloning your repo and try it out myself.  I created a pull request, see https://github.com/kieker-monitoring/kieker/pull/100. Any feedback welcome :-)

Cheers,
Andreas
