### ISSUE TITLE
Lexical error when project contains Kotlin Code

### ISSUE THREAD

**Issue by JLLeitschuh** [aaschmid/gradle-cpd-plugin#22]
This plugin tries to feed in Kotlin source code into CPD when the project is a mixed Java/Kotlin project.

The plugin should ignore Kotlin source code.

**Comment by JLLeitschuh** [comment]
This seems to resolve the problem (Gradle Kotlin DSL):
```kotlin
tasks.withType<Cpd> {
    exclude { it.file.extension.contains("kt") }
}
```

**Comment by aaschmid** [comment]
Hi @JLLeitschuh,

thanks for your issue and one possible solution. 
Is you Java code separated from your Kotlin source code? If yes, you should also be able to use `source = sourceSets.main.java` to only use CPD for Java source code. Does that help?

Cheers,
Andreas

**Comment by JLLeitschuh** [comment]
Hi @aaschmid 
I think that the gradle kotlin compiler plugin adds the `kotlin` source directory to the `sourceSets.main.java`. At least, that's what seems to be going on.

The Kotlin compiler allows you to have you kotlin source code in a separate `kotlin` directory or mix it with your java code in the `java` directory.

**Comment by aaschmid** [comment]
As this is a CPD library issue, I will close it for now. If you have any ideas, don't hesitate to reopen it.

**Comment by JLLeitschuh** [comment]
Sorry, the problem isn't that I have Kotlin code under the `src/java` directory. The problem is because the IntelliJ Kotlin Gradle plugin adds the `src/kotlin` directory to the Java Source Sets so the CPD plugin picks them up.

**Comment by aaschmid** [comment]
hm ... still not really an issue of that plugin, isn't it?
Don't know why the kotlin plugin does mixup the java and kotlin source code in one `sourceSet`.

**Comment by JLLeitschuh** [comment]
So that you could put Kotlin code in the Java directory or Java code in the Kotlin directory.

**Comment by aaschmid** [comment]
Easier maybe but it feels a bit hacky and unclean ...
Thanks for your thoughts
