### ISSUE TITLE
Any gradle command to start the detection ?

### ISSUE THREAD

**Issue by gauravarora90** [aaschmid/gradle-cpd-plugin#26]
I have configured it. But I am not sure, how it will start detecting the duplicate code. Any gradle command to start the detection process ?

**Comment by aaschmid** [comment]
As I assume on your question that you haven't specified any dependencies like `analyze.dependsOn(cpdCheck)` you can directly call

```
gradle cpdCheck
```

to start the Copy-Paste-Detection.

Does that help?

Cheers,
Andreas

**Comment by gauravarora90** [comment]
Where to define this dependency ? in my gradle file itself, or any config file in the root level of my project ?

**Comment by aaschmid** [comment]
Yes, you can put it into the `build.gradle` file of your project, where you also added the `cpd` plugin as described in https://github.com/aaschmid/gradle-cpd-plugin/blob/master/README.md

**Comment by aaschmid** [comment]
As there is no more response since a long time the issue might be fixed :-)
Otherwise don't hesitate to reopen it...
