### ISSUE TITLE
cpd can't handle the sign "`"

### ISSUE THREAD

**Issue by contrudar** [aaschmid/gradle-cpd-plugin#27]
Hello, I have Java and Kotlin code in one project. Everything worked well until the kotlin line was added:
`DialogEntity.ID.`in`(dialogIdList))`
and i got this error
Lexical error in file path\List101Database.kt at line 51, column 50.  Encountered: "`" (96), after : ""

Can it be somehow fixed? thanks in advance

**Comment by aaschmid** [comment]
Hi @contrudar, 

unfortunately CPD cannot handle Kotlin syntax. Can you just exclude the Kotlin source files using 
```
tasks.withType(Cpd) {
    exclude "*.kt"
}
``` 

see also #22

**Comment by contrudar** [comment]
thx
