### ISSUE TITLE
Changing cpdCheck source seems to have no affect

### ISSUE THREAD

**Issue by LethiferousMoose** [aaschmid/gradle-cpd-plugin#34]
I've tried following your readme and I still cannot seem to make cpdCheck stop running on tests and scala.
This does not work:
```groovy
   cpd {
        language = 'java'
        skipLexicalErrors = true
        toolVersion = '6.12.0'
    }

   cpdCheck {
      source = sourceSets.main.java
   }
```
This also does not work
```groovy
    cpd {
        language = 'java'
        skipLexicalErrors = true
        toolVersion = '6.12.0'
    }
    
    tasks.cpdCheck {
        source = sourceSets.main.java
    }
```
If I turn on debug logging, I still see it "Tokenizing" tests and scala code. I'm also very confused why it is trying to read a changelog,md file located in my `src` directory.

**Comment by LethiferousMoose** [comment]
My guess is it has to do with `CpdExecutor`, you create the `cpdCheck` task in `CpdPlugin`, then create the executor, which calls `getSource()` on the `cpdCheck` tasks, which makes a copy of the task sources, so now it's not possible to change the source associated with the `CpdExecutor`

**Comment by aaschmid** [comment]
Hi @LethiferousMoose,

I am not sure by heart but I think this has something to do with how scala and java plugin integrates with another. I will dive deeper into it and give you feedback.

Meanwhile you can try
```gradle
tasks.withType(Cpd) {
    exclude "*.scala"
}
```
There is also an `include` method, see https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceTask.html.

Does that help you for now?

**Comment by aaschmid** [comment]
@LethiferousMoose any news on this?

**Comment by LethiferousMoose** [comment]
I haven't done any more with it. CPD was finding too many false positives on our code base and I decided against using it because it wasn't adding enough value to justify it.

**Comment by aaschmid** [comment]
OK, thanks for the answer. I will close the issue but don't hesitate to reopen if it is still a problem :-)
