### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by dtbwije** [aaschmid/gradle-cpd-plugin#49]
What is the LifecycleBasePlugin that is mentioned in the readme. Could not find it any where.

**Comment by aaschmid** [comment]
It is the base plugin for almost every other plugin which the defines the basic lifecycle methods such as `clean`, `check`, `build`... See https://docs.gradle.org/current/javadoc/org/gradle/language/base/plugins/LifecycleBasePlugin.html

**Comment by aaschmid** [comment]
Bow clear @dtbwije? Can we close this?

**Comment by aaschmid** [comment]
Closing because of no response. Don't hesitate to reopen if required.
