### ISSUE TITLE
Lexical error. Encountered: token recognition error at: '& '

### ISSUE THREAD

**Issue by AndyHao11** [aaschmid/gradle-cpd-plugin#62]
I got the following error when trying to execute cpdCheck 
> A failure occurred while executing internal.worker.CpdAction
   > Lexical error in file /myfile.java at line 203, column 21.  Encountered: token recognition error at: '& '

The line of code is 
`if (((int) buf[i] & 0xff) < 0x10)`

Is there a way to either workaround or suppress the error?

**Comment by aaschmid** [comment]
Any news on this @AndyHao11?

**Comment by AndyHao11** [comment]
@aaschmid  Sorry, a stupid mistake on my side. This is resolved. It turned out I was checking the wrong language.

**Comment by aaschmid** [comment]
No worrries, therefore I will close this issue
