### ISSUE TITLE
Gradle KTS integration

### ISSUE THREAD

**Issue by mustafa-antonio** [aaschmid/gradle-cpd-plugin#64]
Hello,

I couldn't find this issue here so I thought about writing new one. Is there a way to integrate this plugin with Gradle KTS syntax? `cpd` part was easy to set up but I don't know how to configure `cpdCheck` in Kotlin. Is this supported by this plugin or still in development? Some updated README would be nice.

Any kind of help or info is appreciated.

I'm using newest (3.3) version of this plugin.

All the best.

**Comment by aaschmid** [comment]
I am using it with KTS syntax in [junit-dataprovider](https://github.com/TNG/junit-dataprovider/blob/main/build.gradle.kts#L366-L379) myself:

```kts
configure<de.aaschmid.gradle.plugins.cpd.CpdExtension> {
    // Use Java 8 and later to execute cpd successfully
    toolVersion = "6.13.0"
}

tasks.named<de.aaschmid.gradle.plugins.cpd.Cpd>("cpdCheck") {
    ignoreFailures = true
    minimumTokenCount = 25
    setSource(files(
            // only check java source code
            subprojects.flatMap { it.the<SourceSetContainer>()["main"].java.srcDirs },
            subprojects.flatMap { it.the<SourceSetContainer>()["test"].java.srcDirs }
    ))
}
```

**Comment by mustafa-antonio** [comment]
Thank you, will let you know how this works once I'm back to configuring CPD again this week.

**Comment by mustafa-antonio** [comment]
Sorry I've forgot to close this issue - thx for help!
