### ISSUE TITLE
Generate two records

### ISSUE THREAD

**Issue by Nils-Ehmke** [aaschmid/gradle-cpd-plugin#7]
As mentioned in #5, I would expect the plugin to generate two records: one for the main sources and one for the test sources. It should be possible to configure the source folders for both records (and the path to the test sources should behave as in  #4).

**Comment by aaschmid** [comment]
HI @Nils-Ehmke, I am changing some parts of the plugin. After asking some colleagues, most of them would also prefer having one check for ```main``` and ```test``` sources. I am sorry, but this does not get fixed.
