### ISSUE TITLE
Deprecation Message: The option skipLexicalErrors is deprecated. Use failOnError instead. 

### ISSUE THREAD

**Issue by vector-jnajjar** [aaschmid/gradle-cpd-plugin#75]
The newest version of CPD (from PMD 7.3.0) deprecated this option. 
It is read from in de.aaschmid.gradle.plugins.cpd.CpdExtension#skipLexicalErrors
and written from the taskMapping in com.vector.cfg.build.cfgpmd.cpd.CfgCpdPlugin#setupTaskDefaults 

Could you please update this to failOnError.

See https://github.com/pmd/pmd/blob/master/docs/pages/release_notes_old.md#deprecated-api for details.

**Comment by aaschmid** [comment]
Thanks. Do you have a clue how the already existing option `ignoreFailures` from Gradle itself acts in that regard or can you try it?

**Comment by jhonnen** [comment]
`VerificationTask.ignoreFailures` is not a replacement, as this would not fail the build anymore on duplicated code.

**Comment by vector-jnajjar** [comment]
Hi Andreas,

https://docs.pmd-code.org/apidocs/pmd-core/7.3.0/net/sourceforge/pmd/cpd/CPDConfiguration.html#setSkipLexicalErrors(boolean) states that the new flag also configures whether lexical errors should fail the build or not.

But as I read 
https://github.com/pmd/pmd/blob/6f505b965c028c17847cbc50d6ff431af0a22f5a/pmd-cli/src/main/java/net/sourceforge/pmd/cli/internal/CliExitCode.java#L36

I feel like the behavior "there were files I could not read, but the files I could read contained no CPD violation so I report success" cannot be reached (anymore?). However is this state needed?

**Comment by aaschmid** [comment]
Ok, I will try to add this option within the next days (PR also welcome) if I find the time...

**Comment by aaschmid** [comment]
I now played around 1 hour with `failOnError` and `failOnViolation` but don't get their actual behaviors such that I will skip the corresponding tests for now and will create the new release. 

Maybe I overlook something, or I miss the forest for the trees but I neither have the time nor the muse for diving deeper...

However, both parameters are now available and can be forwarded ...
